packaging yolov7
Ridecell/yolov7 pull request #1
Opened 2023-10-23 21:59 UTC by abhilashbalachandran

download coco data set to test:

```
bash scripts/get_coco.sh
```
Download weights from here: [weights](https://github.com/WongKinYiu/yolov7#performance)
Train:
```
python train.py --epochs 1 --device 0 --batch-size 8 --data data/coco.yaml --img 640 640 --cfg cfg/training/yolov7.yaml --weights <weights-file> --name yolov7 --hyp data/hyp.scratch.p5.yaml
```

Test:
```
python detect.py --weights <weights-file> --conf 0.25 --img-size 640 --source inference/images/horses.jpg
```

2023-10-24 17:08 UTC, napratin requested changes
Besides the inline comments, I would suggest moving the folders back out of the `yolov7` package to the root of the repo: `cfg/`, `data/`, `deploy/`, `scripts/`, `tools/` (essentially, anything that does not have .py files with classes / functions that someone may need to import).

`export.py` should be moved to `scripts/` (nothing to import); `hubconf.py` and `detect.py` can also be moved to `scripts/` (but they have some functions defined, so could stay in the package as well).

`test.py` and `train.py` can stay inside the package; you may need to update any readme/instructions to change from running them as:
`python test.py ...`
to:
`python -m yolov7.test ...`
(please check and verify!)

Lastly, there are some images that look like may have been accidentally removed (see files changed); please add them back in.

When this PR is approved, I'd recommend using the 'Squash and Merge' option - that will collapse all your minor commits & corrections into a single commit and keep the history clean.

2023-10-24 17:08 UTC, napratin commented on setup.py
> +    description='OneFormer: One Transformer to Rule Universal Image Segmentation',
```suggestion
    description='YOLOv7: Trainable bag-of-freebies for real-time object detection',
```

2023-10-24 17:08 UTC, napratin commented on setup.py
> +"""YOLOv7: Trainable bag-of-freebies sets new state-of-the-art for real-time object detectors"""
```suggestion
"""YOLOv7: Trainable bag-of-freebies for real-time object detection"""
```

2023-10-24 17:08 UTC, napratin commented on yolov7/data/hyp.scratch.p5.yaml
> +fliplr: 0.0  # image flip left-right (probability)
is this change associated with this refactor? (if not, maybe revert it)

2023-10-24 17:08 UTC, napratin commented on yolov7/export.py
>  import torch.nn as nn
Remove `sys.path.append('./')` few lines above (and from anywhere else in the repo - otherwise we won't be able to test if the package is being installed correctly).

2023-10-24 17:08 UTC, napratin commented on yolov7/export.py
>  if __name__ == '__main__':
Looks like `export.py` is a script, with no useful imports, so I'd recommend moving this to the `scripts/` folder.

2023-10-24 17:08 UTC, napratin commented on yolov7/models/yolo.py
> +# sys.path.append('./')  # to run '$ python *.py' files in subdirectories
Once tested to work correctly, you can delete this line (no need to leave it commented out - might give others wrong ideas!).

2023-10-24 17:08 UTC, napratin commented on yolov7/utils/aws/resume.py
> +#sys.path.append('./')  # to run '$ python *.py' files in subdirectories
Same - can remove this line once tested.

2023-10-24 17:08 UTC, napratin commented on yolov7/utils/wandb_logging/wandb_utils.py
>  from utils.general import colorstr, xywh2xyxy, check_dataset
Same - can remove the commented out line. Also, should these utils imports have a `yolov7.` prefix?

2023-10-25 18:05 UTC, abhilashbalachandran commented on setup.py
> +    description='OneFormer: One Transformer to Rule Universal Image Segmentation',
https://github.com/WongKinYiu/yolov7 Official website says detectors. Have kept the same description

2023-10-25 18:05 UTC, abhilashbalachandran commented on setup.py
> +"""YOLOv7: Trainable bag-of-freebies sets new state-of-the-art for real-time object detectors"""
https://github.com/WongKinYiu/yolov7 Official website says detectors. Will keep the same description :)

2023-10-25 18:06 UTC, abhilashbalachandran commented on yolov7/export.py
>  import torch.nn as nn
removed

2023-10-25 18:07 UTC, abhilashbalachandran commented on yolov7/export.py
>  if __name__ == '__main__':
moving to scripts/

2023-10-25 18:07 UTC, abhilashbalachandran commented on yolov7/models/yolo.py
> +# sys.path.append('./')  # to run '$ python *.py' files in subdirectories
removing

2023-10-25 18:08 UTC, abhilashbalachandran commented on yolov7/utils/aws/resume.py
> +#sys.path.append('./')  # to run '$ python *.py' files in subdirectories
Haven't tested resume.py. Leaving it for now. It might be required to have aws setup for testing this.

2023-10-25 18:09 UTC, abhilashbalachandran commented on yolov7/utils/wandb_logging/wandb_utils.py
>  from utils.general import colorstr, xywh2xyxy, check_dataset
Haven't tested this. Leaving the comments on for now. Packages are imported from correct namespaces

2023-10-25 20:01 UTC, napratin reviewed
Just some minor path corrections in `scripts/get_coco.sh` - other than that, changes look good to me!

2023-10-25 20:01 UTC, napratin commented on scripts/get_coco.sh
> +d='./yolov7' # unzip directory
```suggestion
d='./' # unzip directory
```

The datasets are meant to be downloaded to the root of the repo. See download command above (`./scripts/get_coco.sh`) and `.gitignore` file while ignores anything under `coco/` in the root.

2023-10-25 20:01 UTC, napratin commented on scripts/get_coco.sh
> +d='./yolov7/coco/images' # unzip directory
```suggestion
d='./coco/images' # unzip directory
```
(same as above - this is meant to go in the root of the repo, not inside the package)

2023-10-25 20:01 UTC, napratin commented on setup.py
> +"""YOLOv7: Trainable bag-of-freebies sets new state-of-the-art for real-time object detectors"""
(Ha ha, I know! But that's the title of the paper. Anyways, no biggie!)

2023-10-25 20:01 UTC, napratin commented on yolov7/utils/aws/resume.py
> +#sys.path.append('./')  # to run '$ python *.py' files in subdirectories
Hmmm, it's weird why this is under `utils/aws/` - there's nothing AWS-specific about it.

Yeah, should be fine either way.

2023-10-26 03:32 UTC, napratin approved these changes
Thanks for the instructions - worked as expected!

I'm leaving a minor comment about the annotations file path - this was hardcoded in the original repo anyways, so you don't have to correct it; but if you feel like it, you can make another contribution towards addressing tech debt :)

2023-10-26 03:32 UTC, napratin commented on yolov7/test.py
> +        anno_json = f'{parent_path}/coco/annotations/instances_val2017.json'  # annotations json
This might be fine for now (while the package is installed in dev mode); but when it is built into a pip wheel and installed, anything outside the package folder will not be present (cfg, data, etc.) - or at least not guaranteed to be at the same relative path.

Also the name of the dataset is hardcoded here (`coco`). Trying to train or test on a new dataset will require manual changes to this script.

Instead, I was wondering why this `annotations` path is not included in the `--data` file (i.e. `data/coco.yaml` in this case)? E.g. something like:
```yaml
# COCO 2017 dataset http://cocodataset.org

...

# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train: ./coco/train2017.txt  # 118287 images
val: ./coco/val2017.txt  # 5000 images
test: ./coco/test-dev2017.txt  # 20288 of 40670 images

# annotations
annotations: ./coco/annotations/instances_val2017.json

...
```

You should be able to then fetch it here in the `test()` function as: `anno_json = data['annotations']`

2023-10-27 17:16 UTC, merged